  functional:
    - Требование 1: Пользователь должен иметь возможность искать товары по ключевому слову или категории
     - Требование 2: Пользователь должен иметь возможность фильтровать товары
     - Требование 3: Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
     - Требование 4: Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  non-functional:
    - Требование 1: Сайт должен быть безопасным и защищать данные пользователя
    - Требование 2: Сайт должен иметь мобильную версию
    - Требование 3: Важно, чтобы сайт мог обрабатывать большое количество трафика
    implicit:
      - Требование 1: Интрефейс сайта должен быть удобен для пользователя 
        - Требование 2: Сайт должен быть быстрым в загрузке 
          - Требование 3: Сайт должен быть адаптивным, с учетом разных устройств и 
            - Требование 4: Сайт мог обрабатывать большой обьем трифика и запросов 
